// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3BvEQihb5rWldZC_6W67Z2koqomugOd8',
    appId: '1:1053271767994:web:4fe8430fe3049319767b83',
    messagingSenderId: '1053271767994',
    projectId: 'gayaid',
    authDomain: 'gayaid.firebaseapp.com',
    storageBucket: 'gayaid.firebasestorage.app',
    measurementId: 'G-SWEDZF0KM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuj1lP_RZizcopoGQS4YYH0XGpTvnP_ks',
    appId: '1:1053271767994:android:6e6dcb43ac95c39d767b83',
    messagingSenderId: '1053271767994',
    projectId: 'gayaid',
    storageBucket: 'gayaid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOpXKotSH_TyRCTo8m3l0scu_Cd9iZ-M',
    appId: '1:1053271767994:ios:02deb22320ce6393767b83',
    messagingSenderId: '1053271767994',
    projectId: 'gayaid',
    storageBucket: 'gayaid.firebasestorage.app',
    iosBundleId: 'com.example.gayaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOpXKotSH_TyRCTo8m3l0scu_Cd9iZ-M',
    appId: '1:1053271767994:ios:02deb22320ce6393767b83',
    messagingSenderId: '1053271767994',
    projectId: 'gayaid',
    storageBucket: 'gayaid.firebasestorage.app',
    iosBundleId: 'com.example.gayaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3BvEQihb5rWldZC_6W67Z2koqomugOd8',
    appId: '1:1053271767994:web:2847d63bf8141ff8767b83',
    messagingSenderId: '1053271767994',
    projectId: 'gayaid',
    authDomain: 'gayaid.firebaseapp.com',
    storageBucket: 'gayaid.firebasestorage.app',
    measurementId: 'G-VCX3BDDMYN',
  );
}
